export const GET_USERS = "GET_USERS";
export const GET_ITEMS_REQUESTED = "GET_ITEMS_REQUESTED"
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const GET_USERS_FAILED = "GET_USERS_FAILED"

